OBSTACLES:
  - name: obs1
    arrt: 12
    status: true
    tasks:
      - id: 48
        wait: 40
        position: [36, 12, -1.5]
      - id: 48
        wait: 40
        position: [36, 12, -1.5]
  - name: obs2
    arrt: 30
    status: true
    tasks:
      - id: 84
        wait: 50
        position: [24, 24, -1.5]
      - id: 84
        wait: 50
        position: [24, 24, -1.5]
  - name: obs3
    arrt: 40
    status: true
    tasks:
      - id: 126
        wait: 50
        position: [36, 36, -1.5]
      - id: 126
        wait: 50
        position: [36, 36, -1.5]
