RECH_POINTS:
  - name: rech1
    arrt: 0
    status: true
    tasks:
      - id: 104
        wait: 0
        position: [0, 32, -1.5]
      - id: 104
        wait: 0
        position: [0, 32, -1.5]
  - name: rech2
    arrt: 0
    status: true
    tasks:
      - id: 58
        wait: 0
        position: [24, 16, -1.5]
      - id: 58
        wait: 0
        position: [24, 16, -1.5]
  - name: rech3
    arrt: 0
    status: true
    tasks:
      - id: 11
        wait: 0
        position: [44, 0, -1.5]
      - id: 11
        wait: 0
        position: [44, 0, -1.5]
  - name: rech4
    arrt: 0
    status: true
    tasks:
      - id: 1
        wait: 0
        position: [4, 0, -1.5]
      - id: 1
        wait: 0
        position: [4, 0, -1.5]
  - name: rech5
    arrt: 0
    status: true
    tasks:
      - id: 159
        wait: 0
        position: [12, 48, -1.5]
      - id: 159
        wait: 0
        position: [12, 48, -1.5]
  - name: rech6
    arrt: 0
    status: true
    tasks:
      - id: 165
        wait: 0
        position: [36, 48, -1.5]
      - id: 165
        wait: 0
        position: [36, 48, -1.5]
