TASK:
  - name: task1
    arrt: 5
    status: true
    tasks:
      - id: 32
        wait: 3
        position: [32, 8, -1.5]
      - id: 62
        wait: 5
        position: [8, 20, -1.5]  
  - name: task2
    arrt: 10
    status: true
    tasks:
      - id: 25
        wait: 3
        position: [4, 8, -1.5]
      - id: 91
        wait: 10
        position: [28, 28, -1.5]
