TASK:
  - name: task1
    arrt: 5
    status: true
    tasks:
      - id: 1
        wait: 3
        position: [7, 8.5, -1.5]
      - id: 2
        wait: 5
        position: [16, 15, -1.5]  
  - name: task2
    arrt: 10
    status: true
    tasks:
      - id: 3
        wait: 3
        position: [5.5, 5.5, -1.5]
      - id: 4
        wait: 10
        position: [2, 19, -1.5]
  